### ISSUE TITLE
Vertica 7.1.0 is not supported

### ISSUE THREAD

**Issue by afsungur** [jamescasbon/vertica-sqlalchemy#11]
When I try to connect Vertica 7.1.0 I am getting the below message ( version string has been changed ):
Mac OS X 10.9.4, unixODBC 2.3.2
Traceback (most recent call last):
  File "main2.py", line 13, in <module>
    sessionx.execute('select \* from tables')
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 977, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 847, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 315, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1729, in contextual_connect
    self.pool.connect(),
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 332, in connect
    return _ConnectionFairy._checkout(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 626, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 433, in checkout
    rec = pool._do_get()
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 945, in _do_get
    return self._create_connection()
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 278, in _create_connection
    return _ConnectionRecord(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 409, in __init__
    exec_once(self.connection, self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/event/attr.py", line 247, in exec_once
    self(_args, *_kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/event/attr.py", line 257, in **call**
    fn(_args, *_kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 1203, in go
    return once_fn(_arg, *_kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/strategies.py", line 165, in first_connect
    dialect.initialize(c)
  File "/Library/Python/2.7/site-packages/sqlalchemy/connectors/pyodbc.py", line 142, in initialize
    super(PyODBCConnector, self).initialize(connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1560, in initialize
    super(PGDialect, self).initialize(connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 232, in initialize
    self._get_server_version_info(connection)
  File "build/bdist.macosx-10.9-intel/egg/sqlalchemy_vertica/base.py", line 99, in _get_server_version_info
AssertionError: Could not determine version from string 'Vertica Analytic Database v7.1.0-1'

**Comment by bradsokol** [comment]
It turns out this was a configuration error. I created a `vertica.ini` file that looks like this:

```
[Driver]
DriverManagerEncoding=UTF-16
# ...
```

And then set the location in the environment:

```
export VERTICAINI=~/path/to/my/vertica.ini
```

After these changes, the test case above passed on OS X.

**Comment by bradleyhurley** [comment]
@jamescasbon - I would be willing to take over this project.  I have access to several Vertica clusters, and would like to merge in some of the upstream changes.

Thanks,
Brad
